### ISSUE TITLE
Add citation.cff

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1574]
https://twitter.com/natfriedman/status/1420122675813441540

**Comment by priyanshuone6** [comment]
This might help https://citation-file-format.github.io/cff-initializer-javascript/

**Comment by tinosulzer** [comment]
Nice, can you do this @priyanshuone6 ?

**Comment by priyanshuone6** [comment]
Okay

**Comment by brosaplanella** [comment]
Also, this might be a good time to create a Zenodo DOI for PyBaMM and link it so a new DOI is provided for each release.

**Comment by tinosulzer** [comment]
Kind of prefer people citing the paper than a Zenodo DOI tbh

**Comment by brosaplanella** [comment]
I think it is better too, but will the cff to cite the paper or the code? If the latter, it is better to give it a DOI.

**Comment by priyanshuone6** [comment]
let me know if there are any changes
```
---
authors: 
  -
    family-names: Sulzer
    given-names: Valentin
  -
    family-names: Marquis
    given-names: Scott G.
  -
    family-names: Timms
    given-names: Robert
  -
    family-names: Robinson
    given-names: Martin
  -
    family-names: Chapman
    given-names: S. Jon
cff-version: "1.1.0"
date-released: 2021-06-08
doi: "10.5334/jors.309"
keywords: 
  - battery modelling
  - expression tree
  - python
  - symbolic differentiation
license: "BSD 3-Clause"
message: "If you use PyBaMM, please cite it using the following metadata."
repository-code: "https://github.com/pybamm-team/PyBaMM"
title: "Python Battery Mathematical Modelling (PyBaMM)"
...
```
