### ISSUE TITLE
Switch to `ruff format`

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3477]
Ruff can now format files!

Would mostly require changes in `pyproject.toml` and `.pre-commit-config.yaml`

**Comment by Rjchauhan18** [comment]
Hello @Saransh-cpp 
Can i make PR for this ?

As mention in this issue https://github.com/pybamm-team/PyBaMM/issues/3476 
- Refering from this [repositery](https://github.com/astral-sh/ruff-pre-commit/blob/8a43105c597ef7067b5507451f4f1b07e5f6e26d/README.md?plain=1#L68) if we add  like this
```
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.1"
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --ignore=E741, --exclude=__init__.py]

      - id: ruff-format
        args: [--check]

```

 **Do you want it with `--check` or without?**
